Vagrant.configure("2") do |config|
  #config.vm.box       = 'devbox-2-0-4'
  #config.vm.box_url   = 'devbox-2-0-4.box'
  #config.vm.hostname = 'am-devbox-2-0-3'

  # Rails & HTTP development
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  # Mailcatcher
  config.vm.network :forwarded_port, guest: 1080, host: 1080
  # PostgreSQL
  config.vm.network :forwarded_port, guest: 5432, host: 5432
  # MySQL
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  # MongoDB
  config.vm.network :forwarded_port, guest: 27017, host: 27017
  # Memcache
  config.vm.network :forwarded_port, guest: 11211, host: 11211
  # Redis
  config.vm.network :forwarded_port, guest: 6379, host: 6379
  # ElasticSearch
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  config.ssh.forward_agent = true

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", nfs: true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2000"]

    # Enable shared clipboard
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
end
