#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'postgresql'
cookbook 'nodejs'
cookbook 'database'
#cookbook 'chef-rvm', :git => 'https://github.com/fnichol/chef-rvm', :ref => 'v0.9.0'
#cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
#cookbook 'ruby_build'
cookbook 'mongodb'
#cookbook 'phantomjs'