#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'chef-locale', git: 'https://github.com/deepak/chef-locale.git'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'#, '3.0.2'
cookbook 'memcached'
cookbook 'postgresql'
cookbook 'nodejs'
cookbook 'database'
cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm'
cookbook 'mongodb'
cookbook 'phantomjs'
cookbook 'chef-mc', git: 'https://github.com/lunsher/chef-mc.git'
cookbook 'build-essential'#, '~> 1.4.4'
cookbook 'nfs'
cookbook 'imagemagick'
cookbook 'java'
cookbook 'elasticsearch'
cookbook 'redisio'
